plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0' // Spring Boot 버전 3.4.0으로.
    id 'io.spring.dependency-management' version '1.1.0'
}

group 'me.scpark'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22) // java는 oracle jdk 22
    }
}


repositories {
    mavenCentral()
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}


test {
    useJUnitPlatform()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // 스프링 데이터 JPA
    runtimeOnly 'com.h2database:h2' // 인메모리 데이터베이스
    compileOnly 'org.projectlombok:lombok' // 반복적인 메서드 작성 작업을 줄여주는 롬복
    annotationProcessor 'org.projectlombok:lombok'
}

dependencies {
    // 1. JUnit 5 의존성 (Jupiter)
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'

    // 2. Gradle 8/9 버전에서 테스트 실행을 위해 필수적인 런처
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// 3. Gradle에게 JUnit Platform을 사용한다고 명시
test {
    useJUnitPlatform()
}

dependencies {
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}